name: Publish
on:
  push:
    branches:
      - 'dev/1.10'
      - 'dev/1.13'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Upload to Maven
        run: ./gradlew publish -PVintageForgeUsername="${{ secrets.MAVEN_USERNAME }}" -PVintageForgePassword="${{ secrets.MAVEN_PASSWORD }}" --stacktrace
